#!/bin/bash
export GCE_PROJECT=pen-testing-c2
export GCE_PEM_FILE_PATH=~/pen_testing_c2.json
export GCE_EMAIL=$(grep client_email $GCE_PEM_FILE_PATH | sed -e 's/  "client_email": "//g' -e 's/",//g')
gcloud config set project $GCE_PROJECT
