---
#file: evilnginx.yml

- name: Create GCE Server
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_name: "evilnginx"
    tag_names: "http,https,phishing"
  roles:
    - gceserver 
  tags: phishing

- name: Create phishing setup
  hosts: evilnginx
  roles:
    - common
    - evilnginx
  tags: phishing 
