---
#file: gophish.yml
- name: Create GCE Server
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_name: "gophish"
    tag_names: '["http","https","phishing"]'
  roles:
    - gceserver 
  tags: phishing

- name: Create phishing setup
  hosts: gophish
  connection: ssh
  vars:
    instance_name: "gophish"
    tag_names: '["http","https","phishing"]'
  roles:
    - common
    - gophish
  tags: phishing 
